import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        // English
        'en_US': {
          'Dashboard': 'Dashboard',
          'Apps': 'Apps',
          'Authentication': 'Authentication',
          'Pages': 'Pages',
          'Calender': 'Calender',
          'Chat': 'Chat',
          'Email': 'Email',
          'Invoices': 'Invoices',
          'Contacts': 'Contacts',
          'Blog': 'Blog',
          'Login': 'Login',
          'Register': 'Register',
          'Recover Password': 'Recover Password',
          'Lock Screen': 'Lock Screen',
          'Log Out': 'Log Out',
          'Confirm Mail': 'Confirm Mail',
          'Email Verification': 'Email Verification',
          'Two Step Verification': 'Two Step Verification',
          'Starter Page': 'Starter Page',
          'Maintenance': 'Maintenance',
          'Coming Soon': 'Coming Soon',
          'Timeline': 'Timeline',
          'FAQs': 'FAQs',
          'Pricing': 'Pricing',
          'Error 404': 'Error 404',
          'Error 500': 'Error 500',
          'Forms': 'Forms',
          'Basic Elements': 'Basic Elements',
          'Validation': 'Validation',
          'Advanced Plugins': 'Advanced Plugins',
          'Editors': 'Editors',
          'File Upload': 'File Upload',
          'Wizard': 'Wizard',
          'Mask': 'Mask',
          'Tables': 'Tables',
          'Bootstrap Basic': 'Bootstrap Basic',
          'DataTables': 'DataTables',
          'Responsive': 'Responsive',
          'Editable': 'Editable',
        },
        // Spanish
        'es_ES': {
          'Dashboard': 'Panel',
          'Apps': 'Aplicaciones',
          'Authentication': 'Autenticación',
          'Pages': 'Páginas',
          'Calender': 'Calandrar',
          'Chat': 'Charlar',
          'Email': 'Correo electrónico',
          'Invoices': 'Facturas',
          'Contacts': 'Contactos',
          'Blog': 'Blog',
          'Login': 'Acceso',
          'Register': 'Registro',
          'Recover Password': 'Recuperar contraseña',
          'Lock Screen': 'Bloquear pantalla',
          'Log Out': 'Cerrar sesión',
          'Confirm Mail': 'Confirmar correo',
          'Email Verification': 'Verificacion de email',
          'Two Step Verification': 'Verificación de dos pasos',
          'Starter Page': 'Página de inicio',
          'Maintenance': 'Mantenimiento',
          'Coming Soon': 'Muy pronto',
          'Timeline': 'Línea de tiempo',
          'FAQs': 'Preguntas frecuentes',
          'Pricing': 'Precios',
          'Error 404': 'Error 404',
          'Error 500': 'Error 500',
          'Forms': 'Formularios',
          'Basic Elements': 'Elementos basicos',
          'Validation': 'Validación',
          'Advanced Plugins': 'Complementos avanzados',
          'Editors': 'Editores',
          'File Upload': 'Subir archivo',
          'Wizard': 'Mago',
          'Mask': 'Mascarilla',
          'Tables': 'Mesas',
          'Bootstrap Basic': 'Bootstrap básico',
          'DataTables': 'Tablas de datos',
          'Responsive': 'Sensible',
          'Editable': 'Editable',
          'Inbox': 'Bandeja de entrada',
          'Read Email': 'Leer el correo electrónico',
          'Invoice List': 'Lista de facturas',
          'Invoice Detail': 'Detalles de la factura',
          'User Grid': 'Cuadrícula de usuario',
          'User List': 'Lista de usuarios',
          'Profile': 'Perfil',
          'Blog Grid': 'Cuadrícula de blogs',
          'Blog List': 'Lista de blogs',
          'Blog Details': 'Detalles del blog',
        },
        // German
        'de_CH': {
          'Dashboard': 'Armaturenbrett',
          'Apps': 'Apps',
          'Authentication': 'Authentifizierung',
          'Pages': 'Seiten',
          'Calender': 'Kalander',
          'Chat': 'Plaudern',
          'Email': 'Email',
          'Invoices': 'Rechnungen',
          'Contacts': 'Kontakte',
          'Blog': 'Blog',
          'Login': 'Anmeldung',
          'Register': 'Registrieren',
          'Recover Password': 'Passwort wiederherstellen',
          'Lock Screen': 'Bildschirm sperren',
          'Log Out': 'Ausloggen',
          'Confirm Mail': 'Mail bestätigen',
          'Email Verification': 'E-Mail-Verifizierung',
          'Two Step Verification': 'Zweistufige Verifizierung',
          'Starter Page': 'Starterseite',
          'Maintenance': 'Wartung',
          'Coming Soon': 'Demnächst',
          'Timeline': 'Zeitleiste',
          'FAQs': 'FAQs',
          'Pricing': 'Preisgestaltung',
          'Error 404': 'Fehler 404',
          'Error 500': 'Fehler 500',
          'Forms': 'Formen',
          'Basic Elements': 'Grundelemente',
          'Validation': 'Validierung',
          'Advanced Plugins': 'Erweiterte Plugins',
          'Editors': 'Herausgeber',
          'File Upload': 'Datei-Upload',
          'Wizard': 'Magier',
          'Mask': 'Maske',
          'Tables': 'Tische',
          'Bootstrap Basic': 'Bootstrap Basic',
          'DataTables': 'Datentabellen',
          'Responsive': 'Responsiv',
          'Editable': 'Bearbeitbar',
          'Inbox': 'Posteingang',
          'Read Email': 'E-Mail lesen',
          'Invoice List': 'Rechnungsliste',
          'Invoice Detail': 'Rechnungs-Details',
          'User Grid': 'Benutzerraster',
          'User List': 'Benutzerliste',
          'Profile': 'Profil',
          'Blog Grid': 'Blog-Raster',
          'Blog List': 'Blog-Liste',
          'Blog Details': 'Blogdetails',
        },
        // Italian
        'it_CH': {
          'Dashboard': 'Pannello di controllo',
          'Apps': 'App',
          'Authentication': 'Autenticazione',
          'Pages': 'Pagine',
          'Calender': 'Calendario',
          'Chat': 'Chiacchierata',
          'Email': 'E-mail',
          'Invoices': 'Fatture',
          'Contacts': 'Contatti',
          'Blog': 'Blog',
          'Login': 'Login',
          'Register': 'Registrati',
          'Recover Password': 'Recupera la password',
          'Lock Screen': 'Blocca schermo',
          'Log Out': 'Disconnettersi',
          'Confirm Mail': 'Conferma posta',
          'Email Verification': 'Verifica email',
          'Two Step Verification': 'Verifica in due passaggi',
          'Starter Page': 'Pagina iniziale',
          'Maintenance': 'Manutenzione',
          'Coming Soon': 'Prossimamente',
          'Timeline': 'Sequenza temporale',
          'FAQs': 'Domande frequenti',
          'Pricing': 'Prezzo',
          'Error 404': 'Errore 404',
          'Error 500': 'Errore 500',
          'Forms': 'Forme',
          'Basic Elements': 'Elementi basici',
          'Validation': 'Convalida',
          'Advanced Plugins': 'Plugin avanzati',
          'Editors': 'Redattori',
          'File Upload': 'Upload di file',
          'Wizard': 'Procedura guidata',
          'Mask': 'Maschera',
          'Tables': 'Tabelle',
          'Bootstrap Basic': 'Bootstrap di base',
          'DataTables': 'DataTable',
          'Responsive': 'Reattivo',
          'Editable': 'Modificabile',
          'Inbox': 'Posta in arrivo',
          'Read Email': 'Leggi e-mail',
          'Invoice List': 'Elenco fatture',
          'Invoice Detail': 'Dettagli della fattura',
          'User Grid': 'Griglia utente',
          'User List': 'lista degli utenti',
          'Profile': 'Profilo',
          'Blog Grid': 'Griglia del blog',
          'Blog List': 'Elenco dei blog',
          'Blog Details': 'Dettagli del blog',
        },
        //Russian
        'ru_RU': {
          'Dashboard': 'Панель приборов',
          'Apps': 'Программы',
          'Authentication': 'Аутентификация',
          'Pages': 'Страницы',
          'Calender': 'Календарь',
          'Chat': 'Чат',
          'Email': 'Электронная почта',
          'Invoices': 'Счета',
          'Contacts': 'Контакты',
          'Blog': 'Блог',
          'Login': 'Авторизоваться',
          'Register': 'Регистр',
          'Recover Password': 'Восстановить пароль',
          'Lock Screen': 'Экран блокировки',
          'Log Out': 'Выйти',
          'Confirm Mail': 'Подтвердить почту',
          'Email Verification': 'Подтверждение адреса электронной почты',
          'Two Step Verification': 'Двухэтапная проверка',
          'Starter Page': 'Стартовая страница',
          'Maintenance': 'Обслуживание',
          'Coming Soon': 'Вскоре',
          'Timeline': 'График',
          'FAQs': 'Часто задаваемые вопросы',
          'Pricing': 'Цены',
          'Error 404': 'Ошибка 404',
          'Error 500': 'Ошибка 500',
          'Forms': 'Формы',
          'Basic Elements': 'Основные элементы',
          'Validation': 'Проверка',
          'Advanced Plugins': 'Расширенные плагины',
          'Editors': 'Редакторы',
          'File Upload': 'Файл загружен',
          'Wizard': 'Волшебник',
          'Mask': 'Маска',
          'Tables': 'Столы',
          'Bootstrap Basic': 'Базовая начальная загрузка',
          'DataTables': 'Таблицы данных',
          'Responsive': 'Отзывчивый',
          'Editable': 'Редактируемый',
          'Inbox': 'Входящие',
          'Read Email': 'Читать электронную почту',
          'Invoice List': 'Список счетов',
          'Invoice Detail': 'Сведения о счете',
          'User Grid': 'Пользовательская сетка',
          'User List': 'Список пользователей',
          'Profile': 'Профиль',
          'Blog Grid': 'Сетка блога',
          'Blog List': 'Список блогов',
          'Blog Details': 'Подробности блога',
        },
      };
}
